### ISSUE TITLE
Overwriting other launch options

### ISSUE THREAD

**Issue by markspo** [SheffeyG/CheatDeck#11]
I have a few GOG games that I installed, and have them all share a prefix folder using

`STEAM_COMPAT_DATA_PATH="/home/deck/.steam/steam/steamapps/compatdata/experimental" STEAM_COMPAT_MOUNTS=/run/media/mmcblk0p1 WINE_LARGE_ADDRESS_AWARE=0 PROTON_FORCE_LARGE_ADDRESS_AWARE=0 %command%`

When setting CheatDeck, it blows out the current option, and replaces it, thus creating a new prefix folder.  I've attempted to append the CheatDeck options with the current options, but it won't load the trainer.  I've attempted to put the trainer in the prefix directory, and in my /home/deck/Downloads, still nothing.

Is there a way to fix this?

**Comment by SheffeyG** [comment]
@markspo The overwrite problem should be fixed in the new pre release v0.2.0, you can install and test it from url

**Comment by eXhumer** [comment]
@SheffeyG Can this be reopened due to issue with the current implementation? I have a `WINEDLLOVERRIDES="dinput8=n,b"` in some of my games like RE4 (to add REFramework) and other kinds of mod support. CheatDeck replaces the entry with `WINEDLLOVERRIDES="dinput8` and breaks running the application until I go and manually fix the launch options back.

**Comment by SheffeyG** [comment]
@eXhumer You are right, a fix pr is appreciated
