### ISSUE TITLE
Issues with Custom Options

### ISSUE THREAD

**Issue by eXhumer** [SheffeyG/CheatDeck#16]
I noticed that a way to add custom launch options via CheatDeck is being added, but I found several bugs with the current implementation where modifying the option with a new key or value has few issues with it. If you modify only the value of an existing custom option, the new value seems to be never applied even when you save. If you modify the key of the custom option, it will not remove the old key and will instead add a new key=value pair alongside the old key=value pair.

Additionally the value field doesn't appear to be touch interactable and I have to use the DPad to access the value field.

**Comment by eXhumer** [comment]
Also, deleting the custom option doesn't appear to remove the option from launch options. I have to manually go to launch options and remove it.

**Comment by SheffeyG** [comment]
The modified options with a new field would be a "new" options, so the changes from custom list (local storage) will never affect the launcher options, unless you explicitly toggle and save it, because some other apps like EmuDeck and Heroic launcher make their own launch options.
The new value seems to be never applied is a bug, I didn't check the value change, glad you pointed it out, it should be fixed now. A modified value will be show as a disabled option.
I am not sure if there are any better ways to do it or suggestions, so I will keep this issue open

**Comment by SheffeyG** [comment]
The custom options items are stored at local storage, they are not for only the current game, you can quick access them in any other games, so the change of the custom items will never affect the current games launch options

**Comment by eXhumer** [comment]
I tested the custom options with the current latest commit in main. Everything is working except the the value field not being selectable with touch. I tried my best to see if it can be fixed, but to no avail. I don't think the issue is with CheatDeck itself, as such, I will close this issue.
