### ISSUE TITLE
Feature request: Pass argument to Executable

### ISSUE THREAD

**Issue by ACiDxCHRiST** [SheffeyG/CheatDeck#24]
I would like to start Cheat Engine.exe and load the cheat table so I need the command to be "path/to/Cheat\ Engine.exe cheat_table.ct"

Can you add an option below where you select the EXE to pass arguments.

**Comment by eXhumer** [comment]
It should be possible by modifying the `PROTON_REMOTE_DEBUG_CMD` environment variable. Add an unescaped space` ` instead of `\ ` and pass the argument for the executable after it. If the argument has spaces in it, make sure to escape it with `\ ` instead of ` `.

In your case, suppose the `PROTON_REMOTE_DEBUG_CMD="path/to/Cheat\ Engine.exe"` is set currently, you will need to modify it to `PROTON_REMOTE_DEBUG_CMD="path/to/Cheat\ Engine.exe cheat_table.ct"` or if the path to cheat_table.ct contains spaces `PROTON_REMOTE_DEBUG_CMD="path/with\ spaces/to/cheat_table.ct"`.

**Comment by eXhumer** [comment]
[Proton uses python's `shlex.split` to parse the remote debug command out of the environment variable](https://github.com/ValveSoftware/Proton/blob/bc4d2acf3ba8c3edd8ba915e520996ed811eaf3c/proton#L1419).

**Comment by SheffeyG** [comment]
Also the host disk would be mount as `z:\home\deck\...` in the proton container. you can try `PROTON_REMOTE_DEBUG_CMD="path/to/Cheat\ Engine.exe\ z:\\home\\deck\\path\\to\\cheat_table.ct"`
referance  [here](https://github.com/ValveSoftware/Proton/issues/7377#issuecomment-1904858961)

**Comment by ACiDxCHRiST** [comment]
Thanks, I edited the launch option from:
PROTON_REMOTE_DEBUG_CMD="/home/deck/Cheat\ Engine\ 7.5/Cheat\ Engine.exe" ...

to:
PROTON_REMOTE_DEBUG_CMD="/home/deck/Cheat\ Engine\ 7.5/Cheat\ Engine.exe cheat_table.ct" ...

It works as desired since the table is in the same folder.
